### ISSUE TITLE
Inactive players and Tanner

### ISSUE THREAD

**Issue by t3hc0rr0d3r** [GreyWolfDev/Werewolf#283]
When inactive players are lynched authomatically for not taking part in votes, if they were Tanner they win anyway. This is a bug that can be easily abused for an easy win.

**Comment by parabola949** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/9USaDYfc/11-test)

**Comment by parabola949** [comment]
Can you clarify?  There is no automatic lynch in the code, for any role, for any reason

**Comment by renyhp** [comment]
We tested it, and it didn't happen. The code doesn't link the AFK people with the lynched either. Are you sure you haven't see this happen for any other reason? (eg the Tanner, even if being AFK, was lynched by the majority of the alive players)

**Comment by t3hc0rr0d3r** [comment]
I can assure people are lynched authomatically when not taking part in votes for two times (it's a sort of penalty for afkers), or at least this happened when i started this topic. Once the "afker" was a tanner, so the game ended.

**Comment by renyhp** [comment]
As Para said, that is not called "lynching". That is a penalty, and, if you read carefully, it doesn't mention lynching. Nor does the code link in any way that penalty to lynching. Still, if the majority of people vote for that person, it is "ALSO" lynched. So, if the majority of people voted for the Tanner you saw, he still won, not because of being AFK, but because the people voted for him. Can you please check if that is the case? If it is, this behaviour is intended.

**Comment by Olgabrezel** [comment]
Well I think everything has been said. Tanner will only win if actually lynched, no matter if afk the same day or not. And that was intended.
