### ISSUE TITLE
End Game List Suggestion

### ISSUE THREAD

**Issue by FirewoodLoki** [GreyWolfDev/Werewolf#36]
I think it is better to display the end game list as below:

**Suggestion 1**
Won:
(Cupid Icon) Peter: (Alive Icon) Alive (Lover Heart Icon)
(Mason Icon) John: (Alive Icon) Alive (Lover Heart Icon)
(Villager Icon) John: (Dead Icon) Dead
(Detective Icon) Peter: (Dead Icon) Dead
Lost:
(Wolf Icon) Mary: (Dead Icon) Dead
(Wolf Icon) Sally: (Dead Icon) Dead
(Tanner Icon) Taylor: (Dead Icon) Dead

**Suggestion 2**
Icon Change
Lover 💘
Alive ❤
Seer 🔮
Cultist ⚰
Cult Hunter ⚜

**Suggestion 3**
Please include the ":" mark in the string "PlayersAlive", because I want to use full "︰" version for the Chinese version instead. Not a big deal tho.

**Comment by SilasSit** [comment]
Icons are businesses of string editing in xml...?

**Comment by Olgabrezel** [comment]
Well, about Suggestion 1: We can't put only the role's icon (without the role name) because we don't have it - there is no seperated string in the language files for just the icon. Other than that, it's pretty much just rearranged from the current one and I believe that can stay the way it is.

About Suggestion 2: After years of those roles we can't suddenly change the icons. Not anymore. Sorry xD I'm quite late.

And about suggestion 3: That would make all other language files look strange until they are updated - we can't do that. Sorry, closing this issue.
