### ISSUE TITLE
Tanner and winning

### ISSUE THREAD

**Issue by zzAlMoo** [GreyWolfDev/Werewolf#378]
If someone doesn't vote for 2 turns dies.. In one game with my friend veryone voted for the tanner(he didn't vote the turn before) so that he would die, he didn't vote in the current turn neither and so he won

**Comment by gabrieldluca** [comment]
It's happening because players that died for inactivity are still being considered for the lynch (as long as it's the same day), so it's _"natural"_ for the Tanner to win. I've ran into this issue with a different role.

![Screenshot](https://i.imgur.com/QeaUTtK.png)

I can't, however, tell whether this should be an expected behavior or not.

**Comment by Olgabrezel** [comment]
Well, even tho it doesn't make sense to 100%, it is intended behavior as @gabrieldluca stated. The tanner **was** lynched and therefore he wins, no matter if he dies of AFK the same turn.
