### ISSUE TITLE
Stolen Wild child role can get to see wolf team.

### ISSUE THREAD

**Issue by NeverEndingXD** [GreyWolfDev/Werewolf#390]
I'm hope this is unintended ;X

You are a wild child! Pick a player to be your 'role model' - if they die, you become a werewolf.
Choice accepted. - kuttoos:panda_face:
Your role got stolen! You are now a villager :person_with_blond_hair:, plowing your fields all day.
**kuttoos🐼 has died! In your rage, you have become a werewolf! Your new teammates are: NeverEndingXD,**

To explain the situation clearly. The wild child selects a target in n1, gets stolen while targets dies in a normal thief game (meaning converted to Lowly Villager) while getting to know of the "wolf team"

(If there is already a similar bug report like this in git, or if the bug is intended, kindly disregard this)

**Comment by Olgabrezel** [comment]
It is not a bug, just bad luck, and the messages got sent in wrong order. What actually happened is this:

> You are a wild child! Pick a player to be your 'role model' - if they die, you become a werewolf.
Choice accepted. - kuttoos🐼

Here, the WC was still WC and picket kuttoos as their role model.

> kuttoos🐼 has died! In your rage, you have become a werewolf! Your new teammates are: NeverEndingXD,

Here, the WC turned WW and saw all teammates, as usual.

> Your role got stolen! You are now a villager 👱, plowing your fields all day.

Here, the WC (that is now WW) got stolen and became a villager. The thief became WW. That is because the thief can actually steal wolves in normal thief mode.

So, after all, a bad coincidence, but not a bug. A similar thing could happen if the thief just steals a wolf in first night - the wolf becomes villager and knows all other wolves. But that was intended.
