### ISSUE TITLE
snow wolf freezing

### ISSUE THREAD

**Issue by siyamakazizi** [GreyWolfDev/Werewolf#434]
if a snow wolf freeze a player, can the player talk or must be temp-banned?? please specify this certain rule in your description of snow wolf role. thank you all so very much

**Comment by Olfi01** [comment]
That is a rule that needs to be defined group by group, since some groups also allow deadtalk. The role just declares that a player cannot perform their action if they're frozen.

In my opinion, the frozen person should be allowed to talk, the snow wolf is supposed to only hinder villagers with night activity. But as I said, it's a decision each group will have to make it themselves.
