### ISSUE TITLE
Real time Werewolf

### ISSUE THREAD

**Issue by Handyfon** [GreyWolfDev/Werewolf#471]
Please add an option to set the game speed to real time, so that villagers can vote at day (8 a.m. to 8 p.m.) and werewolfes/roles can vote at night(8 p.m. to 12 p.m.)

**Comment by Olgabrezel** [comment]
Sadly this is hardly possible, because the nodes would have to handle way more games at the same time... If you have an idea how it could be implemented codewise in a well working way, feel free to come to [Grey Wolf Support on Telegram](https://t.me/GreyWolfSupport) and talk to us about it, or make a pull request. Else, please refer to issue #17 that's already opened.
