### ISSUE TITLE
Graveyard

### ISSUE THREAD

**Issue by SalisaZr** [GreyWolfDev/Werewolf#642]
As Ch visit gravedigger and fall in the grave!

**Comment by OlgabrezelPrivate** [comment]
That is intended. Quoting `/aboutGraveDigger`:
> Everyone who visits you has a chance of falling into your newly dug graves, depending on how many graves you dug. Also, the chance is halved for everyone who is on the village team with you.

So a ch, chemist, harlot, guardian angel, ... have a chance to fall into the graves too, which is only half as likely as a wolf, cultist, ... falling into the grave.

**Comment by SalisaZr** [comment]
At first I wanted to use night roles instead of Ch. 
you're right every night roles have chance to fall into grave. 
So can this achievement be added for gravedigger if one of the night roles fall into the grave at night?

**Comment by OlgabrezelPrivate** [comment]
Oh, this was supposed to be an achievement suggestion. I did not understand that at all, your message looked like a bug report.
Achievement suggestions belong in #479, not in new issues.
We are also very unlikely to implement new achievements that involve *playing against your team* (I'm not sure if this would be an instance of that, since the grave digger is not a revealed role).
